CREATE TABLE Users
(
   UserID INT IDENTITY(1,1) PRIMARY KEY,
   FirstName VARCHAR(50) NOT NULL,
   LastName VARCHAR(50) NOT NULL,
   Email VARCHAR(100) NOT NULL,
   Password VARCHAR(50) NOT NULL,
   FileName VARCHAR(100) NULL
)
